Repository Star-Jam/Labor-Man, pull requests merged in 2022-05, with the labels that each got.

#7 マージお願いします
  Assets/Labor-Man/Scenes/EnemyTest.unity
  Assets/Labor-Man/Scenes/EnemyTest.unity.meta
  Assets/Labor-Man/Scripts/Enemy/EnemyBase.cs
Labels: プログラム関連, 未完成

#10 WIP
  Assets/Labor-Man/Scenes/PlayerTest.unity
  Assets/Labor-Man/Scripts/Bullet/BulletBase.cs
  Assets/Labor-Man/Scripts/Manager/StageManager.cs
  Assets/Labor-Man/Scripts/Player/PlayerBase.cs
Labels: プログラム関連, 機能作成

#12 WIP
  Assets/Labor-Man/Prefab/Bullet.prefab
  Assets/Labor-Man/Prefab/Player.prefab
  Assets/Labor-Man/Scenes/PlayerTest.unity
  Assets/Labor-Man/Scenes/Title.unity
  Assets/Labor-Man/Scenes/Title.unity.meta
  Assets/Labor-Man/Scripts/Manager/SceneLoder.cs
Labels: プログラム関連, 機能作成

#14 WIP
  Assets/Labor-Man/Scenes/PlayerTest.unity
  Assets/Labor-Man/Scripts/Player/PlayerBase.cs
Labels: プログラム関連, 機能作成

#16 WIP
  Assets/Labor-Man/Scripts/Player/PlayerBase.cs
Labels: プログラム関連

#15 WIP
  Assets/Labor-Man/Prefab/Player.prefab
  Assets/Labor-Man/Prefab/Stage7.prefab
  Assets/Labor-Man/Prefab/Stage7.prefab.meta
  Assets/Labor-Man/Prefab/Stage8.prefab
  Assets/Labor-Man/Prefab/Stage8.prefab.meta
  Assets/Labor-Man/Prefab/Stage9.prefab
  Assets/Labor-Man/Prefab/Stage9.prefab.meta
  Assets/Labor-Man/Prefab/StartStage.prefab
  Assets/Labor-Man/Prefab/Zako.prefab
  Assets/Labor-Man/Scenes/EnemyTest.unity
  Assets/Labor-Man/Scenes/PlayScene.unity
  Assets/Labor-Man/Scenes/PlayScene.unity.meta
  Assets/Labor-Man/Scripts/Enemy/EnemyBase.cs
  Assets/Labor-Man/Scripts/TestStageManeger.cs
  Assets/Labor-Man/Scripts/TestStageManeger.cs.meta
  UIElementsSchema/UIElements.xsd
  UIElementsSchema/UnityEditor.PackageManager.UI.xsd
  UIElementsSchema/UnityEditor.U2D.Animation.xsd
  UIElementsSchema/UnityEditor.U2D.Layout.xsd
  UIElementsSchema/UnityEditor.UIElements.Debugger.xsd
  UIElementsSchema/UnityEditor.UIElements.xsd
  UIElementsSchema/UnityEngine.UIElements.xsd
Labels: バグ, プログラム関連, 修正が必要

#17 Last
  Assets/Labor-Man/Prefab/Bullet.prefab
  Assets/Labor-Man/Scripts/Bullet/BulletBase.cs
Labels: プログラム関連, 修正が必要

#18 完成
  Assets/Labor-Man/Scenes/Title.unity
  Assets/Labor-Man/Scripts/Player/PlayerBase.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: プログラム関連
